language: node_js
branches:
  only:
    - master
cache:
  diretories:
    - node_modules
notifications:
  email: false
node_js:
  - 'node'
  - 'lts/*'
before_script:
  - npm prune
after_success:
  - npm run cover
  - npm run coverage
  - npm run semantic-release
